import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { IAiProvider } from '../interfaces/ai-provider.interface';

@Injectable()
export class AnthropicProvider implements IAiProvider {
  private readonly logger = new Logger(AnthropicProvider.name);
  private anthropic: any;

  constructor(private configService: ConfigService) {
    try {
      // Dynamic import to handle optional dependency
      this.anthropic = require('@anthropic-ai/sdk');
    } catch (error) {
      throw new Error(
        '@anthropic-ai/sdk package is required. Install it with: npm install @anthropic-ai/sdk',
      );
    }

    const apiKey = this.configService.get<string>('ai.anthropicApiKey');
    if (!apiKey) {
      throw new Error(
        'ANTHROPIC_API_KEY is required when using Anthropic provider',
      );
    }

    this.anthropic = new this.anthropic.Anthropic({ apiKey });
  }

  async generateProposal(prompt: string): Promise<string> {
    try {
      const message = await this.anthropic.messages.create({
        model:
          this.configService.get<string>('ai.anthropicModel') ||
          'claude-3-sonnet-20240229',
        max_tokens: 2000,
        messages: [
          {
            role: 'user',
            content: `You are a professional proposal writer. Generate a detailed, professional proposal based on the following requirements:\n\n${prompt}`,
          },
        ],
      });

      const content = message.content[0]?.text;
      if (!content) {
        throw new Error('No content generated by Anthropic');
      }

      this.logger.log('Proposal generated successfully via Anthropic');
      return content;
    } catch (error) {
      this.logger.error('Failed to generate proposal via Anthropic:', error);
      throw new Error('Failed to generate proposal via Anthropic');
    }
  }
}

