import { Injectable, Logger } from '@nestjs/common';
import { IAiProvider } from '../interfaces/ai-provider.interface';

@Injectable()
export class ConsoleProvider implements IAiProvider {
  private readonly logger = new Logger(ConsoleProvider.name);

  async generateProposal(prompt: string): Promise<string> {
    this.logger.log('AI Proposal Generation (Console/Mock)');
    this.logger.log(`Prompt: ${prompt}`);
    
    // Return a mock proposal for development/testing
    return `Mock Proposal Generated

Based on your request: ${prompt}

This is a placeholder proposal generated by the console provider.
In production, this would be replaced with actual AI-generated content.

Proposal Details:
- Title: Generated Proposal
- Description: This proposal was generated using the console provider for testing purposes.
- Note: Configure an actual AI provider (OpenAI, Anthropic) for production use.`;
  }
}

