import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { IAiProvider } from '../interfaces/ai-provider.interface';

@Injectable()
export class OpenAIProvider implements IAiProvider {
  private readonly logger = new Logger(OpenAIProvider.name);
  private openai: any;

  constructor(private configService: ConfigService) {
    try {
      // Dynamic import to handle optional dependency
      this.openai = require('openai');
    } catch (error) {
      throw new Error(
        'openai package is required. Install it with: npm install openai',
      );
    }

    const apiKey = this.configService.get<string>('ai.openaiApiKey');
    if (!apiKey) {
      throw new Error(
        'OPENAI_API_KEY is required when using OpenAI provider',
      );
    }

    this.openai = new this.openai.OpenAI({ apiKey });
  }

  async generateProposal(prompt: string): Promise<string> {
    try {
      const completion = await this.openai.chat.completions.create({
        model: this.configService.get<string>('ai.openaiModel') || 'gpt-4',
        messages: [
          {
            role: 'system',
            content:
              'You are a professional proposal writer. Generate detailed, professional proposals based on the user\'s requirements.',
          },
          {
            role: 'user',
            content: prompt,
          },
        ],
        temperature: 0.7,
        max_tokens: 2000,
      });

      const content = completion.choices[0]?.message?.content;
      if (!content) {
        throw new Error('No content generated by OpenAI');
      }

      this.logger.log('Proposal generated successfully via OpenAI');
      return content;
    } catch (error) {
      this.logger.error('Failed to generate proposal via OpenAI:', error);
      throw new Error('Failed to generate proposal via OpenAI');
    }
  }
}

